### ISSUE TITLE
Error building android

### ISSUE THREAD

**Issue by morfeus929** [urbanairship/phonegap-ua-push#123]
This are mu plugins 
com.googlemaps.ios 1.13.0 "Google Map iOS SDK for Cordova"
com.phonegap.plugins.nativesettingsopener 1.3 "Native settings"
cordova-plugin-android-support-v4 21.0.1 "Android Support v4"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-contacts 2.1.0 "Contacts"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-googlemaps 1.3.9 "phonegap-googlemaps-plugin"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.3-dev "Whitelist"
cordova-plugin-x-toast 2.5.2 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
urbanairship-cordova 5.1.4 "Urban Airship"

When i try to build android platform i recive error:

Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;
    	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
    	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
    	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
    	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
    	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
    	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    	at com.android.dx.command.dexer.Main.run(Main.java:277)
    	at com.android.dx.command.dexer.Main.main(Main.java:245)
    	at com.android.dx.command.Main.main(Main.java:106)
    
:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

**Comment by rlepinski** [comment]
Looks like a mismatch of google play service versions. Could you run `./gradlew dependencies` and report the output so we can figure out the conflicts?
