### ISSUE TITLE
"Error: Cannot read property 'length' of undefined" during install

### ISSUE THREAD

**Issue by crooy** [urbanairship/phonegap-ua-push#156]
When installing i get this error, i have a list of plugins i use. I am using the  versions for  cordova-cli 6.2.0, cordova-ios 4.3.1 and cordova-android 6.1.0. Using node 6.9.1

```
Subproject Path: CordovaLib
Installing "urbanairship-cordova" for ios
Failed to install 'urbanairship-cordova':TypeError: Cannot read property 'length' of undefined
    at /Users/ronald/Development/withlocals-user-environment/platforms/ios/cordova/lib/Podfile.js:151:17
    at Array.map (native)
    at Podfile.write (/Users/ronald/Development/withlocals-user-environment/platforms/ios/cordova/lib/Podfile.js:147:28)
    at /Users/ronald/Development/withlocals-user-environment/platforms/ios/cordova/Api.js:287:29
    at _fulfilled (/Users/ronald/Development/withlocals-user-environment/platforms/ios/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/ronald/Development/withlocals-user-environment/platforms/ios/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/ronald/Development/withlocals-user-environment/platforms/ios/cordova/node_modules/q/q.js:796:13)
    at /Users/ronald/Development/withlocals-user-environment/platforms/ios/cordova/node_modules/q/q.js:604:44
    at runSingle (/Users/ronald/Development/withlocals-user-environment/platforms/ios/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/ronald/Development/withlocals-user-environment/platforms/ios/cordova/node_modules/q/q.js:125:13)
Error: Cannot read property 'length' of undefined
```

**Comment by crooy** [comment]
Oh it appears to work with cordova-cli 6.4.0

**Comment by hcrowell** [comment]
@crooy Thanks, I will update our README that cordova-cli 6.4.0 is required!

**Comment by hcrowell** [comment]
Updated the readme to require cordova-cli 6.4.0
