### ISSUE TITLE
Problems with installing plugin

### ISSUE THREAD

**Issue by birdwell** [urbanairship/phonegap-ua-push#177]
Hello,

I am unsure why it is failing for ios. I am running the command from the readme.

```
Plugin "urbanairship-cordova" already installed on android.
Plugin "urbanairship-cordova" already installed on browser.
Installing "urbanairship-cordova" for ios
Failed to install 'urbanairship-cordova':CordovaError: Could not find *-Info.plist file, or config.xml file.
    at Object.parseProjectFile [as parse] (.../platforms/ios/cordova/lib/projectFile.js:51:15)
    at Api.addPlugin (.../platforms/ios/cordova/Api.js:224:33)
    at handleInstall (.../.nvm/versions/node/v6.3.1/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:611:6)
    at .../.nvm/versions/node/v6.3.1/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:407:28
    at _fulfilled (.../.nvm/versions/node/v6.3.1/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (.../.nvm/versions/node/v6.3.1/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (.../.nvm/versions/node/v6.3.1/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at .../.nvm/versions/node/v6.3.1/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (.../.nvm/versions/node/v6.3.1/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
Error: Could not find *-Info.plist file, or config.xml file.
```

```
$ cordova -v
6.5.0
```

```
$ pod --version
1.2.0
```

```
$ cordova platforms
Installed platforms:
  android 6.1.2
  browser 4.1.0
  ios 4.3.1
```

**Comment by rlepinski** [comment]
Could you try removing the iOS platform and then re-adding it?

**Comment by birdwell** [comment]
I have tried multiple times removing and adding it.

**Comment by birdwell** [comment]
Sweet, so this time I didn't try to build on xcode before I ran the install and it worked. Any idea why that might be?

**Comment by birdwell** [comment]
I am so happy. I just got the notification test to work! Quick question @rlepinski how do you allow your app to still show the notification if the app is in the foreground?

**Comment by rlepinski** [comment]
@birdwell Only iOS 10 allows showing the notification if its in the foreground. Previous OS versions, apple assumed the app would handle the push. You can set options in the config:

```
<!-- iOS 10 alert foreground notification presentation option -->
<preference name="com.urbanairship.ios_foreground_notification_presentation_alert" value="true | false"/>

<!-- iOS 10 badge foreground notification presentation option -->
<preference name="com.urbanairship.ios_foreground_notification_presentation_badge" value="true | false"/>

<!-- iOS 10 sound foreground notification presentation option -->
<preference name="com.urbanairship.ios_foreground_notification_presentation_sound" value="true | false"/>
```

**Comment by birdwell** [comment]
@rlepinski Thanks so much for you help.
