### ISSUE TITLE
cordova android 7.0.0

### ISSUE THREAD

**Issue by greggreenhaw** [urbanairship/phonegap-ua-push#203]
New builds with the android 7 platform fail

Gregs-Mac-Pro:cordova-dominion-android greggreenhaw$ cordova platform add android@latest
Using cordova-fetch for cordova-android@latest
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.drivedominion.crmsuite
	Name: Dominion_CRM
	Activity: MainActivity
	Android target: android-26
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.0.0
Android Studio project detected
Android Studio project detected
Installing "cordova-plugin-app-version" for android
Installing "cordova-plugin-battery-status" for android
Installing "cordova-plugin-camera" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-device" for android
Installing "cordova-plugin-dialogs" for android
Installing "cordova-plugin-disable-nsapptransportsecurity" for android
Installing "cordova-plugin-file-transfer" for android
Installing "cordova-plugin-file" for android

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
        
Installing "cordova-plugin-inappbrowser" for android
Installing "cordova-plugin-intercom" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-media" for android
Plugin dependency "cordova-plugin-file@5.0.0" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on android.
Installing "cordova-plugin-media-capture" for android
Plugin dependency "cordova-plugin-file@5.0.0" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on android.
Installing "cordova-plugin-printer" for android
Installing "cordova-plugin-splashscreen" for android
Installing "cordova-plugin-statusbar" for android
Installing "cordova-plugin-touchid" for android
Installing "cordova-plugin-vibration" for android
Installing "cordova-plugin-websocket" for android
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
Installing "cordova-plugin-wkwebview-engine" for android
Installing "ionic-plugin-keyboard" for android
Installing "urbanairship-cordova" for android
Error during processing of action! Attempting to revert...
Failed to install 'urbanairship-cordova': Error: Uh oh!
ENOENT: no such file or directory, open '/Users/greggreenhaw/Documents/suite/cordova-dominion-android/platforms/android/AndroidManifest.xml'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.parseElementtreeSync (/Users/greggreenhaw/Documents/suite/cordova-dominion-android/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (/Users/greggreenhaw/Documents/suite/cordova-dominion-android/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/Users/greggreenhaw/Documents/suite/cordova-dominion-android/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at AndroidProject.getCustomSubprojectRelativeDir (/Users/greggreenhaw/Documents/suite/cordova-dominion-android/platforms/android/cordova/lib/AndroidProject.js:105:28)
    at install (/Users/greggreenhaw/Documents/suite/cordova-dominion-android/platforms/android/cordova/lib/pluginHandlers.js:106:46)
    at ActionStack.process (/Users/greggreenhaw/Documents/suite/cordova-dominion-android/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/greggreenhaw/Documents/suite/cordova-dominion-android/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/greggreenhaw/Documents/suite/cordova-dominion-android/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
Error: Uh oh!
ENOENT: no such file or directory, open '/Users/greggreenhaw/Documents/suite/cordova-dominion-android/platforms/android/AndroidManifest.xml'

**Comment by rlepinski** [comment]
Looks like android 7.0.0 introduced a few breaking changes. You can continue to use older android versions until we have a fix. Thanks for reporting this issue.

**Comment by MaxInMoon** [comment]
@rlepinski any news on it?

**Comment by rlepinski** [comment]
@MaxInMoon we are hoping to have a release next week.

**Comment by rlepinski** [comment]
Fixed in 6.9.3
