### ISSUE TITLE
android notification not showing when app background

### ISSUE THREAD

**Issue by ShanmugapriyaDurairaj** [urbanairship/phonegap-ua-push#217]
Not showing notification when app is background

CordovaAirshipReceiver: Received push message. Alert: test2. posted notification: false

if app is opened i am getting below error 

03-20 16:21:34.685 23439-23439/com.tsi.rtat I/CordovaAirshipReceiver: Received push message. Alert: test2. posted notification: false
03-20 16:21:34.685 23439-23439/com..rtat I/System.out: {}
03-20 16:21:34.685 23439-23439/com..rtat W/Bundle: Key google.ttl expected String but value was a java.lang.Integer.  The default value <null> was returned.
03-20 16:21:34.705 23439-23439/com.tsi.rtat W/Bundle: Attempt to cast generated internal exception:
                                                      java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
                                                          at android.os.BaseBundle.getString(BaseBundle.java:944)
                                                          at com.urbanairship.cordova.events.PushEvent.getEventData(PushEvent.java:70)
                                                          at com.urbanairship.cordova.UAirshipPlugin$2.onEvent(UAirshipPlugin.java:185)
                                                          at com.urbanairship.cordova.UAirshipPluginManager.notifyListener(UAirshipPluginManager.java:242)
                                                          at com.urbanairship.cordova.UAirshipPluginManager.pushReceived(UAirshipPluginManager.java:100)
                                                          at com.urbanairship.cordova.CordovaAirshipReceiver.onPushReceived(CordovaAirshipReceiver.java:69)
                                                          at com.urbanairship.AirshipReceiver.handlePushReceived(AirshipReceiver.java:105)
                                                          at com.urbanairship.AirshipReceiver.onReceive(AirshipReceiver.java:77)
                                                          at android.app.ActivityThread.handleReceiver(ActivityThread.java:2739)
                                                          at android.app.ActivityThread.access$2100(ActivityThread.java:165)
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.app.ActivityThread.main(ActivityThread.java:5596)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by rlepinski** [comment]
Only in the background this is happening? Did you enable user notifications ?

**Comment by ShanmugapriyaDurairaj** [comment]
@rlepinski  Foreground and background both we are not getting user notification and   please let me know how to enable user notifications

**Comment by rlepinski** [comment]
Please read https://docs.urbanairship.com/platform/cordova/#send-your-first-push-notification
